# Generated by Django 4.2 on 2025-01-30 08:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Do',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=155, verbose_name='ключ')),
                ('value', models.CharField(max_length=155, verbose_name='значение')),
                ('value2', models.CharField(max_length=155, verbose_name='значение')),
                ('value3', models.CharField(max_length=155, verbose_name='значение')),
                ('value4', models.CharField(max_length=155, verbose_name='значение')),
                ('value5', models.CharField(max_length=155, verbose_name='значение')),
            ],
            options={
                'verbose_name_plural': 'Что мы делаем',
            },
        ),
        migrations.AlterField(
            model_name='settings',
            name='description_contact',
            field=ckeditor.fields.RichTextField(verbose_name='Описание контакта'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='description_cool',
            field=ckeditor.fields.RichTextField(verbose_name='Описание cool'),
        ),
    ]
