# Generated by Django 4.2 on 2025-01-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='заголовок')),
                ('title2', models.CharField(max_length=155, verbose_name='заголовок 2')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='Games2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='заголовок')),
                ('title2', models.CharField(max_length=155, verbose_name='заголовок 2')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Игры-2',
            },
        ),
        migrations.CreateModel(
            name='Games3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='заголовок')),
                ('title2', models.CharField(max_length=155, verbose_name='заголовок 2')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Игры-3',
            },
        ),
        migrations.CreateModel(
            name='Games4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='заголовок')),
                ('title2', models.CharField(max_length=155, verbose_name='заголовок 2')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Игры-4',
            },
        ),
        migrations.CreateModel(
            name='Games5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='заголовок')),
                ('title2', models.CharField(max_length=155, verbose_name='заголовок 2')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Игры-5',
            },
        ),
    ]
