# Generated by Django 4.2 on 2025-01-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_games_games2_games3_games4_games5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('title2', models.CharField(max_length=155, verbose_name='Заголовок 2')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'свяжитесь с нами',
            },
        ),
    ]
