# Generated by Django 4.2 on 2025-01-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Email',
            },
        ),
    ]
